### ISSUE TITLE
Needs configuration file support.

### ISSUE THREAD

**Issue by IonoclastBrigham** [RealFreq/rf_data_server#1]
Possible choices:
- YAML
- Gcfg
- Lua

**Comment by misham** [comment]
Going to use YAML.  There's [Viper](http://spf13.com/project/viper) but that might be overkill.  This would control things such as API tokens, host names, etc.

For configuration of the system as a whole, initialize major components, etc. I think a [Factory Design Pattern](http://en.wikipedia.org/wiki/Factory_method_pattern) would be a better approach.

Though Factory approach is longer-term.

**Comment by IonoclastBrigham** [comment]
YAML is nice since it's well-supported and most implementations are probably well-tested. YAML files are kinda ugly and hard to read, though, IMHO.

I could get onboard with a factory controlled by configuration metadata, if we don't need the power of a full scripting language.

**Comment by misham** [comment]
I think the YAML files will have to be limited in terms of nesting. Also, the configuration(s) would be limited to a specific interface/component.  For example, the logging config, would be in `config/logging.yml` and contain the following format:

``` yaml
graphite:
  host: 127.0.0.1
  port: 10001
influxdb:
  host: 127.0.0.1
  port: 10000
  api:
    key: abc123
```

Or something similar. But it's kept to a minimum.  You could probably break it apart into `graphite.yml` and `influxdb.yml` and have the `logger.yml` specify which interface to use or something.
